"""empty message

Revision ID: 325ec053e2a6
Revises: cc21075b981e
Create Date: 2025-02-08 22:19:04.347698

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '325ec053e2a6'
down_revision = 'cc21075b981e'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('pharmacy', schema=None) as batch_op:
        batch_op.alter_column('contact_number',
               existing_type=sa.TEXT(),
               type_=sa.String(length=20),
               existing_nullable=True)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('pharmacy', schema=None) as batch_op:
        batch_op.alter_column('contact_number',
               existing_type=sa.String(length=20),
               type_=sa.TEXT(),
               existing_nullable=True)

    # ### end Alembic commands ###
